# Generated by Django 5.1.7 on 2025-03-22 19:01

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0004_alter_ticket_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.create_custom_path
            ),
        ),
    ]
