# Generated by Django 5.1.7 on 2025-03-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planetarium",
            "0006_alter_astronomyshow_title_alter_planetariumdome_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="show_themes",
            field=models.ManyToManyField(to="planetarium.showtheme"),
        ),
    ]
